name: Build and Deploy Java Lambda

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        env:
            SAM_STACK_NAME: typeahead-searchitems-service
            SAM_REGION: us-east-1
            SAM_CAPABILITIES: CAPABILITY_IAM

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4.2.1
              with:
                  java-version: '17'
                  distribution: 'corretto'
                  cache: 'maven'

            - name: SAM Build
              run: make build

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.SAM_REGION }}

            - name: Deploy with SAM
              run: |
                  sam deploy --stack-name ${{ env.SAM_STACK_NAME }} --region ${{ env.SAM_REGION }} --capabilities ${{ env.SAM_CAPABILITIES }} --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset
